application:
  name: simple-example-node-mongodb
  project: getting-started-mongodb
  cloud_region: aws/us-west-2
  publicly_accessible: true
databases:
- name: my-mongodb
  type: mongodb
  version: 3.6
routers:
- name: main
  routes:
  - application_name: simple-example-node-mongodb
    paths:
    - /

